### ISSUE TITLE
Accessing both instigating user and target user

### ISSUE THREAD

**Issue by sethwebster** [tute/merit#210] opened 2015-01-15 19:33 UTC
I'm looking to have access to two users in a points definition. Specifically, let's assume there's a video with our 1st user who created it, and a 2nd user who's commenting on it. I want to award points to the creator of a video that receives a comment but only if the commenter (the 2nd user) has not previously commented. In other words, only the first comment by each user awards points to the video creator.

I have 2 points rules set up to award the points, but can't seem to figure out how to get to the user that makes the comment and the video at the same time to do the duplicate checking. I feel like I may be missing something obvious.

If not, would it be possible to perhaps have the context from the after filter available within the block on the rule?

TIA.

**Comment by tute** [comment] 2015-01-16 03:14
It is possible to access the context. Syntax would be similar to:

```ruby
class Comment
  def video_author
    video.author
  end
end

score 10, to: :video_author, on: 'comments#create' do |comment|
  comment.user.comments.empty?
end
```

Closing this issue as it's not a bug in merit, happy to continue further discussion.

**Closed by tute** 2015-01-16 03:14 UTC

**Comment by sethwebster** [comment] 2015-01-16 03:27
Perhaps a better example from me would help. I have a video, which can be "liked" or "favorited". The author of the video should receive points the first time the video is liked by a specific person. The person should not be able to hit the same route multiple times to add more points. In my mind, I want to check in the block and say, has current_user or action_user previously liked this video? If so, no points.

Following your example, I wouldn't be able to look at video.likes and see if the current_user has already done so because I don't have current_user. I am already preventing dupes on the action, but want to prevent duplicate scoring.

Thoughts? And, thanks.

**Comment by tute** [comment] 2015-01-16 03:37
Is a `like` a counter in a `Video`, or an object in itself? If it's an object, `comment` sample code is analogous.

Else, you will want to solve this case at the controller level with the `add_points` call, instead of in the rules file.

A related PR to what you imagine (having current_user in the rules) is in https://github.com/tute/merit/pull/100, but I preferred to solve these cases in the controller actions directly.

**Comment by sethwebster** [comment] 2015-01-16 04:46
In the comment example, how do I get the user that just commented? Sorry if I am being dense.

Video has an array of likes. What I would do is in the rule is look at the Video Author's previous score_points and make sure they hadn't been previously awarded for a like from this viewing user. But, I don't have the required current_user to which I can compare.

Make sense? 

I can go the controller route, though one of my favorite features of your work here is the centralized definitions of the rules. Was hoping not to break with that; feels very clean/

Thanks for responding.

**Comment by tute** [comment] 2015-01-16 19:46
> In the comment example, how do I get the user that just commented? Sorry if I am being dense.

I assume you have a relation to user (author) from comment, so the user that just commented would be `comment.user`.

> Video has an array of likes. What I would do is in the rule is look at the Video Author's previous score_points and make sure they hadn't been previously awarded for a like from this viewing user. But, I don't have the required current_user to which I can compare.

```ruby
score 10, to: :video_author, on: 'likes#create' do |like|
  like.user.likes.where(video: like.video).empty?
end
```

> Make sense?
>
> I can go the controller route, though one of my favorite features of your work here is the centralized definitions of the rules. Was hoping not to break with that; feels very clean/
>
> Thanks for responding.

+1

**Comment by itsdan** [comment] 2015-03-12 11:57
What if I cannot infer the current_user from the association? For example I have a Session model which relates to User with fields `host_id` and `opponent_id`. In controller action I have access to current_player, but I'm not able to access it Merit.
